//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CVA.Core.EtiquetaTermica.DAO {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Query {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Query() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CVA.Core.EtiquetaTermica.DAO.Query", typeof(Query).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT DISTINCT
        ///	OWOR.&quot;ItemCode&quot; || &apos; - &apos; || OWOR.&quot;ProdName&quot; &quot;Item&quot;,
        ///	&apos;Y&apos; &quot;#&quot;,
        ///	ETIQ.&quot;Name&quot; &quot;Etiqueta&quot;,
        ///	ETIQ.&quot;Code&quot;	&quot;CodEtiq&quot;,
        ///	OWOR.&quot;DocEntry&quot;
        ///FROM OWOR
        ///	INNER JOIN &quot;@CVA_ETIQUETA&quot; ETIQ ON (ETIQ.&quot;Code&quot; = OWOR.&quot;U_SO_EtiqPadrao1&quot; OR ETIQ.&quot;Code&quot; = OWOR.&quot;U_SO_EtiqPadrao2&quot;)
        ///WHERE OWOR.&quot;DocNum&quot; = {0}.
        /// </summary>
        internal static string Etiqueta_GetByOrdemProducao {
            get {
                return ResourceManager.GetString("Etiqueta_GetByOrdemProducao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT DISTINCT
        ///	ETIQ.&quot;Code&quot;,
        ///	ETIQ.&quot;Name&quot;
        ///FROM &quot;@SO_ETIQ_PN&quot; ETIQ_PN 
        ///	INNER JOIN &quot;@SO_ETIQ_ITEM&quot; ETIQ_ITEM ON ETIQ_ITEM.&quot;U_CodEtiq&quot; = ETIQ_PN.&quot;U_CodEtiq&quot; AND ETIQ_ITEM.&quot;U_Valida&quot; = &apos;Y&apos;
        ///	INNER JOIN &quot;@CVA_ETIQUETA&quot; ETIQ ON ETIQ.&quot;Code&quot; = ETIQ_ITEM.&quot;U_CodEtiq&quot; AND ETIQ_ITEM.&quot;U_ItemCode&quot; = &apos;{1}&apos;
        ///WHERE ETIQ_PN.&quot;U_CardCode&quot; = &apos;{0}&apos; AND ETIQ_PN.&quot;U_Padrao&quot; = &apos;Y&apos;
        ///ORDER BY ETIQ.&quot;Code&quot;.
        /// </summary>
        internal static string Etiqueta_GetByPN {
            get {
                return ResourceManager.GetString("Etiqueta_GetByPN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///	ITEM.&quot;Code&quot;,
        ///	ETIQ.&quot;Code&quot; 		&quot;Código&quot;,
        ///	ETIQ.&quot;Name&quot; 		&quot;Descrição&quot;,
        ///	IFNULL(ITEM.&quot;U_Padrao&quot;, &apos;N&apos;) &quot;Etiqueta Padrão&quot;,
        ///	IFNULL(ITEM.&quot;U_Valida&quot;, &apos;N&apos;) &quot;Modelo Válido&quot;
        ///FROM &quot;@CVA_ETIQUETA&quot; ETIQ
        ///	LEFT JOIN &quot;@SO_ETIQ_ITEM&quot; ITEM ON ETIQ.&quot;Code&quot; = ITEM.&quot;U_CodEtiq&quot; AND ITEM.&quot;U_ItemCode&quot; = &apos;{0}&apos;
        ///ORDER BY ETIQ.&quot;Code&quot;.
        /// </summary>
        internal static string EtiquetaItem_Get {
            get {
                return ResourceManager.GetString("EtiquetaItem_Get", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO &quot;@SO_ETIQ_ITEM&quot;
        ///(
        ///	&quot;Code&quot;,
        ///	&quot;U_CodEtiq&quot;,
        ///	&quot;U_ItemCode&quot;,
        ///	&quot;U_Padrao&quot;,
        ///	&quot;U_Valida&quot;
        ///)
        ///SELECT IFNULL(MAX(&quot;Code&quot;) + 1, 1), &apos;{0}&apos;, &apos;{1}&apos;, &apos;{2}&apos;, &apos;{3}&apos;
        ///FROM &quot;@SO_ETIQ_ITEM&quot;.
        /// </summary>
        internal static string EtiquetaItem_Insert {
            get {
                return ResourceManager.GetString("EtiquetaItem_Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE &quot;@SO_ETIQ_ITEM&quot;
        ///SET &quot;U_Padrao&quot; = &apos;{1}&apos;, &quot;U_Valida&quot; = &apos;{2}&apos;
        ///WHERE &quot;Code&quot; = {0}.
        /// </summary>
        internal static string EtiquetaItem_Update {
            get {
                return ResourceManager.GetString("EtiquetaItem_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT DISTINCT
        ///	ETIQ.&quot;Code&quot;,
        ///	ETIQ.&quot;Name&quot;
        ///FROM &quot;@SO_ETIQ_ITEM&quot; ETIQ_ITEM
        ///	INNER JOIN &quot;@CVA_ETIQUETA&quot; ETIQ ON ETIQ.&quot;Code&quot; = ETIQ_ITEM.&quot;U_CodEtiq&quot;
        ///WHERE ETIQ_ITEM.&quot;U_ItemCode&quot; = &apos;{0}&apos; AND ETIQ_ITEM.&quot;U_Padrao&quot; = &apos;Y&apos;
        ///ORDER BY ETIQ.&quot;Code&quot;.
        /// </summary>
        internal static string EtiquetaPadrao_GetByItem {
            get {
                return ResourceManager.GetString("EtiquetaPadrao_GetByItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///	PN.&quot;Code&quot;,
        ///	ETIQ.&quot;Code&quot; 		&quot;Código&quot;,
        ///	ETIQ.&quot;Name&quot; 		&quot;Descrição&quot;,
        ///	IFNULL(PN.&quot;U_Padrao&quot;, &apos;N&apos;) &quot;Etiqueta Padrão&quot;
        ///FROM &quot;@CVA_ETIQUETA&quot; ETIQ
        ///	LEFT JOIN &quot;@SO_ETIQ_PN&quot; PN ON ETIQ.&quot;Code&quot; = PN.&quot;U_CodEtiq&quot; AND PN.&quot;U_CardCode&quot; = &apos;{0}&apos;
        ///ORDER BY ETIQ.&quot;Code&quot;.
        /// </summary>
        internal static string EtiquetaPN_Get {
            get {
                return ResourceManager.GetString("EtiquetaPN_Get", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO &quot;@SO_ETIQ_PN&quot;
        ///(
        ///	&quot;Code&quot;,
        ///	&quot;U_CodEtiq&quot;,
        ///	&quot;U_CardCode&quot;,
        ///	&quot;U_Padrao&quot;
        ///)
        ///SELECT IFNULL(MAX(&quot;Code&quot;) + 1, 1), &apos;{0}&apos;, &apos;{1}&apos;, &apos;{2}&apos;
        ///FROM &quot;@SO_ETIQ_PN&quot;.
        /// </summary>
        internal static string EtiquetaPN_Insert {
            get {
                return ResourceManager.GetString("EtiquetaPN_Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE &quot;@SO_ETIQ_ITEM&quot;
        ///SET &quot;U_Padrao&quot; = &apos;{1}&apos;
        ///WHERE &quot;Code&quot; = {0}.
        /// </summary>
        internal static string EtiquetaPN_Update {
            get {
                return ResourceManager.GetString("EtiquetaPN_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select &quot;Code&quot;, &quot;Name&quot;, &quot;U_descricao&quot;,&quot;U_script&quot;,&quot;U_linguagem&quot; , &quot;U_procedure&quot;, &quot;U_local&quot;, &quot;U_procpesq&quot;,&quot;U_caminhoscript&quot;
        ///  from &quot;@CVA_ETIQUETA&quot;
        /// where &quot;Canceled&quot; = &apos;N&apos;
        ///   and &quot;Code&quot; = {0}
        /// order by 1.
        /// </summary>
        internal static string EtiquetaServicesGetTagHana {
            get {
                return ResourceManager.GetString("EtiquetaServicesGetTagHana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select &quot;Code&quot;, &quot;Name&quot;
        ///  from &quot;@CVA_ETIQUETA&quot;
        /// where &quot;Canceled&quot; = &apos;N&apos;
        /// order by 2.
        /// </summary>
        internal static string EtiquetaServicesGetTagListHana {
            get {
                return ResourceManager.GetString("EtiquetaServicesGetTagListHana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select Code, Name
        ///  from [@CVA_ETIQUETA]
        /// where canceled = &apos;N&apos;
        /// order by 2.
        /// </summary>
        internal static string EtiquetaServicesGetTagListSql {
            get {
                return ResourceManager.GetString("EtiquetaServicesGetTagListSql", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select Code, Name, U_descricao, convert(varchar(8000), U_script) as U_script, U_linguagem, U_procedure, U_local, U_procpesq
        ///  from [@CVA_ETIQUETA]
        /// where canceled = &apos;N&apos;
        ///   and code = &apos;{0}&apos;
        /// order by 1.
        /// </summary>
        internal static string EtiquetaServicesGetTagSql {
            get {
                return ResourceManager.GetString("EtiquetaServicesGetTagSql", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT DISTINCT
        ///	ETIQ.&quot;Code&quot;,
        ///	ETIQ.&quot;Name&quot;
        ///FROM &quot;@SO_ETIQ_ITEM&quot; ETIQ_ITEM
        ///	INNER JOIN &quot;@CVA_ETIQUETA&quot; ETIQ ON ETIQ.&quot;Code&quot; = ETIQ_ITEM.&quot;U_CodEtiq&quot;
        ///WHERE ETIQ_ITEM.&quot;U_ItemCode&quot; = &apos;{0}&apos; AND ETIQ_ITEM.&quot;U_Valida&quot; = &apos;Y&apos;
        ///ORDER BY ETIQ.&quot;Code&quot;.
        /// </summary>
        internal static string EtiquetaValida_GetByItem {
            get {
                return ResourceManager.GetString("EtiquetaValida_GetByItem", resourceCulture);
            }
        }
    }
}
